---

fail_fast: false
minimum_pre_commit_version: "2.6.0"

repos:
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        exclude: "templates/.*"

  - # see https://github.com/antonbabenko/pre-commit-terraform
    repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.0
    hooks:
      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_fmt
      - id: terraform_fmt

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_validate
      - id: terraform_validate

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_docs
      - id: terraform_docs
        args:
          - "--args=--config=.terraform-docs.yaml"

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_providers_lock
      - id: terraform_providers_lock

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_tflint
      - id: terraform_tflint
        exclude: 'examples/.*'
        args:
          - "--args=--config=__GIT_WORKING_DIR__/.tflint.hcl"

      - id: terraform_tfsec
        args:
          - "--args=--exclude-downloaded-modules"
          - "--args=--custom-check-dir=__GIT_WORKING_DIR__/.tfsec"
  - repo: https://github.com/aws-quickstart/qs-cfn-lint-rules
    rev: v1.0
    hooks:
      - id: qs-cfn-lint-wrapped
        files: templates/.*(\.(yaml|yml|json|template))
  - repo: https://github.com/aws-ia/pre-commit-hooks
    rev: 3e50b87c2e68f4b1e4c4dce5793120c8c1e7afb5
    hooks:
      - id: git-submodule-sanity-check
        always_run: true
  - repo: local
    hooks:
      - id: restricted-filenames
        name: Check commits for unexpected file extensions
        entry: These files are prohibited and should be removed.
        language: fail
        files: '.*\.(taskcat_overrides.yml)'
