---

fail_fast: false
minimum_pre_commit_version: "2.6.0"

repos:
  - repo: local
    hooks:
      - id: generate-pre-commit-ci-config
        name: Geneate pre-commit config for CI usage
        language: script
        entry: ./hooks/pre-commit-generate.sh
        pass_filenames: false
        files: .pre-commit-config.yaml$
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml

  - # see https://github.com/antonbabenko/pre-commit-terraform
    repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.0
    hooks:
      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_fmt
      - id: terraform_fmt

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_validate
      - id: terraform_validate

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_docs
      - id: terraform_docs
        args:
          - "--args=--config=.terraform-docs.yaml"

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_providers_lock
      - id: terraform_providers_lock

      # see https://github.com/antonbabenko/pre-commit-terraform#terraform_tflint
      - id: terraform_tflint
        args:
          - "--args=--config=__GIT_WORKING_DIR__/.tflint.hcl"

      - id: terraform_tfsec
        args:
          - "--args=--custom-check-dir=__GIT_WORKING_DIR__/.tfsec"
  - repo: https://github.com/aws-quickstart/qs-cfn-lint-rules
    rev: main
    hooks:
      - id: qs-cfn-lint
        files: templates/.*(\.template)?\.(yaml|yml|json)$
