---
root_args:
  fail_fast: false
repo_args:
  "https://github.com/antonbabenko/pre-commit-terraform":
    terraform_tflint:
      meta:
        extension: 'tflint'
      args:
        - "--args=-f json"
